quarkus:
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    sql-load-script: import-dev.sql
  swagger-ui:
    display-request-duration: true
  http:
    same-site-cookie:
      session:
        value: strict
      track:
        value: strict
greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
